### ISSUE TITLE
Add Vibratissimo Documentation

### ISSUE THREAD

**Issue by blackspherefollower** [metafetish/stpihkal#32]
These are a range of simple vibrators, all of the ones we've seen report as "Vibratissimo" and have single motors with the same GATT configuration:

Service UUID: 00001523-1212-efde-1523-785feabcd123
Tx Mode Char: 00001524-1212-efde-1523-785feabcd123
Tx Speed Char: 00001526-1212-efde-1523-785feabcd123
Rx Char: 00001527-1212-efde-1523-785feabcd123

The vibrator will be set to a constant on when mode has been set to 0x03, 0xFF.
After that has been written, the speed can be controlled by writing to the speed characteristic with 0xXX,0x00 (where XX is the speed in the range of 0-255, 0r 0x00-0xFF).

This range of vibrators has a quirk that the Bluetooth advertisement name may be customised.

**Comment by qdot** [comment]
Duplicates #4, closing.
